### ISSUE TITLE
App Crashes when picking Videos after using Image Compress

### ISSUE THREAD

**Issue by Mr-Anonymous** [dmcBig/cordova-plugin-mediaPicker#10]
In my App, I have 2 different buttons. 

First button: Selects images only and this method uses `MediaPicker.compressImage()` to compress image. 

Second button: To select videos only and this method does not use `compressImage()` method at all.

This is what I noticed:

1. When I open the App, upload video first, then it works fine.

2. But, when I upload an image first and then select upload video, select video and press Done, it always crashes.

In other words, the video picker crashes if I try to upload videos after I upload an image that uses `compressImage()` method. My video upload does not use `compressImage` obviously, and if only video is uploaded first straight after launching the app, then its fine. But it crashes if video is picked after picking images.

This is the crash error log:
```

05-18 18:54:21.785 32003 32408 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
05-18 18:54:21.785 32003 32408 E AndroidRuntime: Process: com.example.examplemobile, PID: 32003
05-18 18:54:21.785 32003 32408 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
05-18 18:54:21.785 32003 32408 E AndroidRuntime: 	at com.dmc.mediaPickerPlugin.MediaPicker.compressImage(MediaPicker.java:264)
05-18 18:54:21.785 32003 32408 E AndroidRuntime: 	at com.dmc.mediaPickerPlugin.MediaPicker.compressImage(MediaPicker.java:232)
05-18 18:54:21.785 32003 32408 E AndroidRuntime: 	at com.dmc.mediaPickerPlugin.MediaPicker$1.run(MediaPicker.java:161)
05-18 18:54:21.785 32003 32408 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-18 18:54:21.785 32003 32408 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-18 18:54:21.785 32003 32408 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Mr-Anonymous** [comment]
The Google Play Store crash log shows this:

```
java.lang.NullPointerException: 
  at com.dmc.mediaPickerPlugin.MediaPicker.compressImage (MediaPicker.java:264)
  at com.dmc.mediaPickerPlugin.MediaPicker.compressImage (MediaPicker.java:232)
  at com.dmc.mediaPickerPlugin.MediaPicker$1.run (MediaPicker.java:161)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)
```

**Comment by Mr-Anonymous** [comment]
I did not set the `quality` parameter in `args`. I add quality to `results[i]`. This is how I have it:
```
function buttonClick(format) {

  if (format == 'video') {
    var args = {
        'selectMode': 102, 
        'maxSelectCount': 1, 
    };
  }
  else {
    var args = {
        'selectMode': 100,
        'maxSelectCount': 30
    };

    MediaPicker.getMedias(args, function(results) {
        if (results.length) {
          if (format == 'video') {
              uploadUsingFileTransfer(results[0].path);
          }
          else {
            for (var i = 0; i < results.length; i++) {
                results[i].quality = 30; //when the value is 100,return original image
                MediaPicker.compressImage(results[i], function(compressData) {
                    uploadUsingFileTransfer(compressData.path);
                }, function(e) { console.log(e) });
            }
          }
        }
    }, function (error) {
          // console.log('Error: ' + error);
          alert("cannot obtain pictures");
    });
    
}
```

If I remove the `MediaPicker.compressImage()` then I dont have issues selecting videos after photos. But if the above is in place, then the video picker fails after uploading photos before it.

**Comment by dmcBig** [comment]
sir i think format ==‘video’   there is a problem with the use in  MediaPicker.getMedias callback。
change this 
```
    MediaPicker.getMedias(args, function(results) {
        if (results.length) {
          if (results.mediaType== 'video') {  // change 
              uploadUsingFileTransfer(results[0].path);
          }
          else {
             
          }
        }
    }, function (error) {
    });
```

**Comment by dmcBig** [comment]
update plugin form git ，I'm over the weekend and can only be repaired this way. I can't test

**Comment by Mr-Anonymous** [comment]
no worries. Thank you for that. I will give this a try. Cheers! and have a good weekend.

**Comment by dmcBig** [comment]
sir i fix the bug in npm

**Comment by Mr-Anonymous** [comment]
Awesome. Thank you for the quick fix. I will update my app now. 

This `compressImage` feature is very helpful. I was waiting for this so I can start using this in my iOS App as well.

Thanks heaps.
